version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      development:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
          - "@types/*"
          - "jest*"
          - "ts-jest*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-actions:
        patterns:
          - "*"
